
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.scss';
import { useEffect } from 'react';

const Blog: NextPage = () => {

    useEffect(() => {
        fetch('/api/hello').then(res => res.json()).then(res => console.log(res))
            .catch(err => console.log(err));
    }, [])

    return (
        <div className={styles.container}>
            <Head>
                <title>Lets blog</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <h1 className={styles.title}>
                    Welcome to my blog
                </h1>
                <h2 >How are you?</h2>
            </main>
        </div>
    );
}

export default Blog;